from __future__ import annotations
from typing import Protocol


class IVRProvider(Protocol):
    """Bare interface — swap Exotel/Twilio/Plivo behind this."""

    async def answer_and_prompt(self, call_id: str, prompt_text: str, language: str) -> dict: ...
    async def play_and_record(self, call_id: str, prompt_text: str, language: str,
                              max_seconds: int = 8) -> dict: ...
    async def dtmf_menu(self, call_id: str, prompt_text: str, digits: int = 1) -> dict: ...
    async def hangup(self, call_id: str, farewell: str, language: str) -> None: ...
