from __future__ import annotations
from typing import Protocol


class WhatsAppProvider(Protocol):
    async def send_text(self, to: str, text: str) -> dict: ...
    async def send_voice(self, to: str, audio_url: str) -> dict: ...
    async def send_pack(self, to: str, pack_text: str, centre_location: dict | None) -> dict: ...
    async def fetch_media(self, media_id: str) -> bytes: ...
