"""Generate db/seed/seed_training_centres.sql — two SYNTHETIC training centres
in every Indian district, so every caller has a centre near home.

  * "<District> Skill Development Centre"   technical and service trades
  * "<District> Livelihood Training Centre"  farm, food, textile, craft and
                                              home-based trades

Together the two cover every sector in the jobs data. Each centre sits within
~2 km of the district's coordinates (from the indian_districts migrations), and
offers the courses its district has job openings for: the generated file ends
with `select link_centre_courses();` (migration 0016).

These centres are NOT real. They are tagged
source_url='synthetic://setu-demo/centre', pia_name says so, and the address is
marked as a demo address. Do not use them with real callers.

    python db/seed/gen_training_centres.py
"""
from __future__ import annotations

import random
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import gen_demand_all_india as jobs  # noqa: E402  (sector names + district list)

OUT = HERE / "seed_training_centres.sql"
SOURCE_URL = "synthetic://setu-demo/centre"
rng = random.Random(2027)

LIVELIHOOD = [
    jobs.AGRI, jobs.FOOD, jobs.HANDLOOM, jobs.CRAFTS, jobs.APPAREL, jobs.BEAUTY,
    jobs.CAREGIVING, jobs.LEATHER, jobs.WOOD, jobs.GEMS,
]
SKILL = [s for s in jobs.BASE if s not in LIVELIHOOD]
KINDS = [("skill", "Skill Development Centre", SKILL),
         ("livelihood", "Livelihood Training Centre", LIVELIHOOD)]


def load_district_coords() -> list[tuple[str, str, float, float]]:
    pat = re.compile(r"\('((?:[^']|'')+)','((?:[^']|'')+)',\s*(-?[\d.]+),\s*(-?[\d.]+)\)")
    seen, out = set(), []
    for f in ("0011_indian_districts.sql", "0012_all_india_districts.sql"):
        for d, s, lat, lon in pat.findall((jobs.MIGRATIONS / f).read_text(encoding="utf-8")):
            d, s = d.replace("''", "'"), s.replace("''", "'")
            if d.lower() not in seen:          # first one wins, like the migrations
                seen.add(d.lower())
                out.append((d, s, float(lat), float(lon)))
    return out


def sql_str(v: str) -> str:
    return "'" + v.replace("'", "''") + "'"


def sql_array(items: list[str]) -> str:
    return "array[" + ", ".join(sql_str(x) for x in items) + "]"


def main() -> None:
    districts = load_district_coords()
    rows = []
    for district, state, lat, lon in sorted(districts, key=lambda d: (d[1], d[0])):
        for kind, label, _ in KINDS:
            # ~0.02 degrees is about 2 km: close to the district headquarters.
            clat = round(lat + rng.uniform(-0.02, 0.02), 4)
            clon = round(lon + rng.uniform(-0.02, 0.02), 4)
            rows.append(f"({sql_str(f'{district} {label}')},{sql_str(district)},"
                        f"{sql_str(state)},{clat},{clon},'{kind}')")

    kinds_sql = ",\n".join(f"    ('{k}', {sql_array(secs)})" for k, _, secs in KINDS)
    rows_sql = ",\n".join(rows)
    sql = f"""-- Training centres for every district — {len(rows):,} SYNTHETIC centres
-- ({len(KINDS)} per district in {len(districts)} districts).
-- Generated by db/seed/gen_training_centres.py (deterministic).
-- NOT REAL CENTRES: tagged source_url='{SOURCE_URL}'. For demos only.
-- Each centre offers the courses its district has job openings for, within
-- its sectors (link_centre_courses(), migration 0016).
--
-- Safe to re-run: centres are updated in place (enrollments point at their
-- ids) and their course links are rebuilt.

-- Files are UTF-8; say so explicitly so psql on Windows doesn't read them as WIN1252.
set client_encoding = 'UTF8';

begin;

with kinds (kind, sectors) as (values
{kinds_sql}
), centres (name, district, state, latitude, longitude, kind) as (values
{rows_sql}
)
insert into training_centres
       (name, pia_name, address, district, state, latitude, longitude,
        sectors, active, source_url, evidence_date)
select c.name, 'Synthetic demo centre (not real)',
       'District headquarters, ' || c.district || ' (demo address)',
       c.district, c.state, c.latitude, c.longitude,
       k.sectors, true, '{SOURCE_URL}', current_date
  from centres c join kinds k using (kind)
on conflict (name, district) do update set
    pia_name = excluded.pia_name, address = excluded.address, state = excluded.state,
    latitude = excluded.latitude, longitude = excluded.longitude,
    sectors = excluded.sectors, active = excluded.active,
    source_url = excluded.source_url, evidence_date = excluded.evidence_date;

-- Link every centre to the courses its district has job openings for.
select link_centre_courses();

commit;
"""
    OUT.write_text(sql, encoding="utf-8")
    print(f"wrote {OUT.name}: {len(rows):,} centres in {len(districts)} districts "
          f"(skill: {len(SKILL)} sectors, livelihood: {len(LIVELIHOOD)} sectors)")


if __name__ == "__main__":
    main()
